### ISSUE TITLE
macOS: Clicking menubar icon in one monitor makes the app open in a different monitor

### ISSUE THREAD

**Issue by siddhantgoel** [4gray/tauri-menubar#2] opened 2023-04-27 18:17 UTC
Hey, thanks for setting up this example repository!

I have a two-monitor setup with windows arranged like this:
<img width="593" alt="Screenshot 2023-04-27 at 8 15 10 PM" src="https://user-images.githubusercontent.com/79892/234955232-71fed6fa-5988-40af-8816-546eccf5a2e7.png">

The one on the bottom is my main laptop and the on on the top is a secondary display. The menubar is visible on both the screens.

The problem is if I click the menubar icon in the screen at the bottom, the app opens up at the bottom of the top screen. Is it possible to force the app on the screen from which the icon was clicked?

**Comment by 4gray** [comment] 2023-05-06 07:34
Hey, sounds like a duplicate of #1

**Closed as completed** 2023-05-07 08:28 UTC
